// CLI Util to access MQTT
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/Luzifer/rconfig/v2"
	mqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/gofrs/uuid"
	"github.com/sirupsen/logrus"
)

var (
	cfg = struct {
		LogLevel       string        `flag:"log-level" default:"info" description:"Log level (debug, info, warn, error, fatal)"`
		Message        string        `flag:"message,m" default:"" description:"Message to publish to the topic"`
		MQTTBroker     string        `flag:"mqtt-broker,b" default:"tcp://localhost:1883" description:"Broker URI to connect to scheme://host:port (scheme is one of 'tcp', 'ssl', or 'ws')"`
		MQTTClientID   string        `flag:"mqtt-client-id" default:"" description:"Client ID to use when connecting, must be unique (autogenerated when left empty)"`
		MQTTUser       string        `flag:"mqtt-user,u" default:"" description:"Username to identify against the broker" validate:"nonzero"` //revive:disable-line:struct-tag // nonzero is valid
		MQTTPass       string        `flag:"mqtt-pass,p" default:"" description:"Password to identify against the broker" validate:"nonzero"` //revive:disable-line:struct-tag // nonzero is valid
		MQTTTimeout    time.Duration `flag:"mqtt-timeout" default:"10s" description:"How long to wait for the client to complete operations"`
		OutputFormat   string        `flag:"output-format,o" default:"log" description:"How to output received messages (One of 'log', 'csv', 'jsonl')"`
		QOS            int           `flag:"qos" default:"1" description:"QoS to use (0 - At most once, 1 - At least once, 2 - Exactly once)"`
		ReceiveOnce    bool          `flag:"receive-once,1" default:"false" description:"Exit after receiving one message"`
		Retain         bool          `flag:"retain" default:"false" description:"Retain message on topic"`
		Timeout        time.Duration `flag:"timeout" default:"0" description:"How long to listen for messages (0 = infinite)"`
		Topics         []string      `flag:"topic,t" default:"" description:"Topic to subscribe / publish to"`
		VersionAndExit bool          `flag:"version" default:"false" description:"Prints current version and exits"`
	}{}

	version = "dev"
)

func initApp() error {
	rconfig.AutoEnv(true)

	if err := rconfig.ParseAndValidate(&cfg); err != nil {
		return fmt.Errorf("parsing CLI options: %w", err)
	}

	if cfg.MQTTClientID == "" {
		cfg.MQTTClientID = uuid.Must(uuid.NewV4()).String()
	}

	l, err := logrus.ParseLevel(cfg.LogLevel)
	if err != nil {
		return fmt.Errorf("parsing log-level: %w", err)
	}
	logrus.SetLevel(l)

	return nil
}

func main() {
	var err error
	if err = initApp(); err != nil {
		logrus.WithError(err).Fatal("initializing app")
	}

	if cfg.VersionAndExit {
		fmt.Printf("mqttcli %s\n", version) //nolint:forbidigo // fine for version print
		os.Exit(0)
	}

	var cmd string
	if len(rconfig.Args()) > 1 {
		cmd = rconfig.Args()[1]
	}

	var runner func(mqtt.Client) error
	switch cmd {
	case "pub":
		runner = publish

	case "sub":
		runner = subscribe

	case "":
		logrus.Fatal("Usage: mqttcli [opts] <pub|sub>")

	default:
		logrus.Fatalf("unknown command %q", cmd)
	}

	if len(cfg.Topics) == 0 || (len(cfg.Topics) == 1 && cfg.Topics[0] == "") {
		logrus.Fatal("No topic(s) specified")
	}

	client := mqtt.NewClient(
		mqtt.NewClientOptions().
			AddBroker(cfg.MQTTBroker).
			SetClientID(cfg.MQTTClientID).
			SetConnectionLostHandler(func(_ mqtt.Client, err error) {
				logrus.WithError(err).Fatal("Connection to broker lost")
			}).
			SetKeepAlive(cfg.MQTTTimeout).
			SetPassword(cfg.MQTTPass).
			SetUsername(cfg.MQTTUser),
	)

	tok := client.Connect()
	if !tok.WaitTimeout(cfg.MQTTTimeout) {
		logrus.Fatal("connecting within timeout")
	}
	if err := tok.Error(); err != nil {
		logrus.WithError(err).Fatal("connecting to broker")
	}

	if err = runner(client); err != nil {
		logrus.WithError(err).Fatal("executing command")
	}
}
